### ISSUE TITLE
[BUG] No error when trying to parse duplicate keys in plugin config dictionary

### ISSUE THREAD

**Issue by Misaka-ZeroTwo** [Exiled-Team/EXILED#1905]
When there is a Dictionary<TKey, TValue> for a plugin's config, and you put a duplicate key value in the plugin config file, EXILED will reset the plugin's config without saying anything (no WARN or ERROR messages are printed in console. A backup file is not created, it just wipes it silently.)

Exiled Version: 7.0.0-rc.5

Example:
```
    OneToOne:
    - original: Scp173
      new: Scp096
      chance: 100
      keep_inventory: true
    OneToOne:
    - original: Scp096
      new: Scp939
      chance: 100
      keep_inventory: true
    OneToOne:
    - original: Scp939
      new: Scp049
      chance: 100
      keep_inventory: true
    OneToOne:
    - original: Scp049
      new: Scp106
      chance: 100
      keep_inventory: true
  ```
